### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by flip111**
propose to deprecate some libraries

@paluh @jvliwanag @srghma  please review. I made it as pull request instead of direct commit for this reason. Maybe we are not really to deprecate all the proposed libraries yet. I'm not sure what use they have. 

rendered can be viewed here: https://github.com/flip111/purescript-codegen.github.io/blob/patch-1/README.md

### CODE REVIEW

**Comment by srghma** [comment]
I don't want to deprecate `ps-cst`




https://github.com/natefaubion/purescript-tidy-codegen/issues/15
I didn't try yet, but maybe I will like doing

```purs
SmartQualifiedName__Simple (mkModuleName $ NonEmpty.singleton "GraphQLClient") (ProperName "GraphQLDefaultResponseScalarDecoder")
```

more than

```purs
```

**Comment by flip111** [comment]
> I don't want to deprecate `ps-cst`

Fair enough, let's keep that then and put it above. Anything else?

**Comment by srghma** [comment]
No, thx for understanding)

**Comment by flip111** [comment]
Oh thanks for merge .. though i was not 100% sure to merge it like this. Specifically @jvliwanag  might also not be ready to list this library as deprecated https://github.com/purescript-codegen/purescript-cst-simple  i don't know what the current situation is. But happy to make another change on reply !

**Comment by jvliwanag** [comment]
I’m ok with the updated docs. Thanks!

**Pull request merged**
